chore: revert mockery v3 update and validate mockery updates (#886)
- reverts #841 and #868
- add ci to validate mock changes
- https://code.forgejo.org/forgejo/runner/pulls/841#issuecomment-53111

<!--start release-notes-assistant-->
<!--URL:https://code.forgejo.org/forgejo/runner-->
- other
  - [PR](https://code.forgejo.org/forgejo/runner/pulls/886): <!--number 886 --><!--line 0 --><!--description Y2hvcmU6IHJldmVydCBtb2NrZXJ5IHYzIHVwZGF0ZSBhbmQgdmFsaWRhdGUgbW9ja2VyeSB1cGRhdGVz-->chore: revert mockery v3 update and validate mockery updates<!--description-->
<!--end release-notes-assistant-->

Reviewed-on: https://code.forgejo.org/forgejo/runner/pulls/886
Reviewed-by: earl-warren <earl-warren@noreply.code.forgejo.org>
Co-authored-by: Michael Kriese <michael.kriese@visualon.de>
Co-committed-by: Michael Kriese <michael.kriese@visualon.de>

diff --git a/.forgejo/workflows/test.yml b/.forgejo/workflows/test.yml
--- a/.forgejo/workflows/test.yml
+++ b/.forgejo/workflows/test.yml
@@ -127,3 +127,35 @@ jobs:
           set -x
           ./forgejo-runner exec --var MY_VAR=testvariable --workflows .forgejo/testdata/var.yml |& tee /tmp/var.out
           grep --quiet 'Success - Main echo "VAR -> testvariable"' /tmp/var.out
+
+  validate-mocks:
+    needs:
+      - build-and-tests
+    name: validate mocks
+    if: vars.ROLE == 'forgejo-coding'
+    runs-on: docker
+    container:
+      image: 'code.forgejo.org/oci/ci:1'
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-go@v5
+        with:
+          go-version-file: go.mod
+
+
+      - name: generate mocks
+        run: |
+          set -ex
+          make deps-tools
+          make generate
+          make fmt
+
+      - name: validate mocks
+        run: |
+          git diff --quiet || {
+            echo "[ERROR] Please apply the changes mockery suggests:"
+            git diff --color=always
+            exit 1
+          }
